# Generated by Django 3.0.2 on 2020-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botskills',
            name='deiscribe',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
